# use template for gitlab pipeline to push main to github 
include:
  - project: "OE-7035/ssz-da/templates/pipeline-templates"
    ref: "feature-extend"
    file: "publish-to-github.yml"

publish-main-to-github:
  extends:
    - .publish-main-to-github

    # dummy change 2